### ISSUE TITLE
Update ERG Facilities

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/solutions-erg-widget#22] opened 2017-10-04 21:27 UTC
Currently, we're using sample data for Naperville for facilities, in the form of a feature service layer. I think that we should build a JavaScript-side input for users to add their own facilities to the widget. I think that we should allow for users to add multiple layers. For example, if they had a separate layer for hospitals, schools, other critical infrastructure, they should be able to add them all in, so the widget can check against multiple facilities at once. According to @kgonzago, allowing for more than one input feature service will impact how the facilities are rendered in the widget. Another option would be making users have one feature service that can have subtypes for different categories of facilities. 

We would need to figure out how to define the fields to show from the facilities feature layers

Current facilities list for reference: 
![image](https://user-images.githubusercontent.com/13024357/31200486-f84fed3c-a90f-11e7-95cb-1e2b807aedd5.png)

**Comment by joebayles** [comment] 2017-10-18 20:15
Duplicate of #58

**Closed by joebayles** 2017-10-18 20:15 UTC
Labels: 0 - Sprint Backlog, A-feature, G-Documentation, G-Research
